codestates-seb/seb41_main_017

client/public/index.html, client/src/App.js, client/src/components/login/IdForm.jsx, client/src/components/login/LoginButton.jsx, client/src/components/login/LoginInputForm.jsx, client/src/components/signup/SignupBtn.jsx, client/src/components/signup/SignupForm.jsx, client/src/pages/sign/login.js
=> #6 - CSS: 로그인 & 회원가입 컴포넌트 디자인 수정

server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java, server/culinari/src/main/java/com/codestates/culinari/order/constant/StatusType.java, server/culinari/src/main/java/com/codestates/culinari/order/controller/OrdersController.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDetailDto.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/OrderDto.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/request/OrderRequest.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderDetailResponse.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/response/OrderResponse.java, server/culinari/src/main/java/com/codestates/culinari/order/entitiy/OrderDetail.java, server/culinari/src/main/java/com/codestates/culinari/order/entitiy/Orders.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/OrderDetailRepository.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/OrdersRepository.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustom.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/order/service/CartService.java, server/culinari/src/main/java/com/codestates/culinari/order/service/OrdersService.java, server/culinari/src/main/java/com/codestates/culinari/order/service/impl/OrdersServiceImpl.java
주문(`Orders`, `OrderDetail`) 관련 DTO를 정의, 수정하고 Create, Read 작성
- 우선적으로 사용자 관련 기능 먼저 작성 (Update, Delete는 이후 추가)
[QueryDSL](http://querydsl.com)
Closes #24 - 주문 관련 기능 정의
주문 관련 기능 정의
=> [BE] 주문 기능 구현

server/culinari/src/main/java/com/codestates/culinari/user/controller/UserController.java, server/culinari/src/main/java/com/codestates/culinari/user/dto/request/ProfilePatchRequest.java, server/culinari/src/main/java/com/codestates/culinari/user/dto/response/ProfileMyPageResponseDto.java, server/culinari/src/main/java/com/codestates/culinari/user/entitiy/Profile.java, server/culinari/src/main/java/com/codestates/culinari/user/service/Impl/ProfileServiceImpl.java, server/culinari/src/main/java/com/codestates/culinari/user/service/ProfileService.java, server/culinari/src/main/java/com/codestates/culinari/user/service/impl/ProfileServiceImpl.java, server/culinari/src/main/java/com/codestates/culinari/user/service/impl/UserServiceImpl.java
- 프로필 수정 추가
- 패키지 이름 변경
- #46
변경사항 모두 완료 했습니다.
this Closes #46
=> [BE] 프로필 수정 구현

client/src/components/service/ManyQuestion.jsx, client/src/components/service/ManyQuestionHeader.jsx, client/src/components/service/ManyQuestionItem.jsx
=> [FE] 자주 묻는 질문 컴포넌트 구현

server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerInquiryController.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CustomerNoticeController.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsInquiryRequest.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsNoticePost.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsInquiryResponse.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsNoticeResponse.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CustomerInquiryControllerTest.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CustomerNoticeControllerTest.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerInquiryServiceTest.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerNoticeServiceTest.java
고객센터  관련 기능(1:1문의, 공지사항)을 테스트 할 수 있는 테스트 코드 작성
- #55 
- #15 
- #55
=> [BE] 고객센터 테스트코드 작성

server/culinari/src/main/java/com/codestates/culinari/customercenter/controller/CsFrequentlyAskedQuestionController.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/CsFrequentlyAskedQuestionDto.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/request/CsFrequentlyAskedQuestionRequest.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/dto/response/CsFrequentlyAskedQuestionResponse.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/entity/CsFrequentlyAskedQuestion.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/CsFrequentlyAskedQuestionRepository.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/querydsl/CsFrequentlyAskedQuestionCustom.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/repository/querydsl/impl/CsFrequentlyAskedQuestionCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/service/CustomerFrequentlyAskedQuestionService.java, server/culinari/src/main/java/com/codestates/culinari/customercenter/service/impl/CustomerFrequentlyAskedQuestionImpl.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/controller/CsFrequentlyAskedQuestionControllerTest.java, server/culinari/src/test/java/com/codestates/culinari/customercenter/service/CustomerFrequentlyAskedQuestionServiceTest.java
- 고객센터 자주묻는 질문 CR 구현
- 성공 테스트 코드 작성
- 자주묻는 질문 카테고리 필터 구현
- #69 
- #69
=> [BE] 고객센터 - 자주묻는 질문 구현 

server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPatch.java, server/culinari/src/main/java/com/codestates/culinari/order/dto/request/CartPost.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/CartRepository.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/OrdersRepository.java, server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/order/service/impl/CartServiceImpl.java, server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/PaymentRequest.java, server/culinari/src/main/java/com/codestates/culinari/payment/dto/request/RefundRequest.java, server/culinari/src/test/java/com/codestates/culinari/order/Stub/Stub.java, server/culinari/src/test/java/com/codestates/culinari/order/controller/OrdersControllerTest.java, server/culinari/src/test/java/com/codestates/culinari/order/service/impl/CartServiceImplTest.java
- 이후 개발에서 이슈와 관련 없는 코드 변동으로 인해 리뷰가 어려워지는 것을 막기 위해 분리해서 리팩토링
- #85 
- This Closes #85
=> [BE] 주문, 결제 관련 코드 리팩토링

client/src/App.js, client/src/components/CheckBox.jsx, client/src/components/Header.jsx, client/src/components/ProductItem.jsx, client/src/constants/BASE_URL.js, client/src/pages/collection/index.js, client/src/pages/productDetail/productContent/CreateInquiry.jsx
신상품, 베스트 페이지 레이아웃 구현, 기능 일부 구현
없음.
#80 - [FE] 신상품, 베스트 페이지 구성 컴포넌트, 레이아웃 구현
1. 카테고리 필터 체크리스트 컴포넌트 구현
2. 신상품, 베스트 페이지 진입 시 헤더 버튼 active 구현
3. 신상품순, 낮은 가격순, 높은 가격순 필터 컴포넌트 구현
4. 신상품, 베스트 페이지 레이아웃 구현
=> [FE] 신상품, 베스트 페이지 구성 컴포넌트, 레이아웃 구현

server/culinari/src/main/java/com/codestates/culinari/global/exception/ExceptionCode.java, server/culinari/src/main/java/com/codestates/culinari/payment/controller/PaymentController.java, server/culinari/src/main/java/com/codestates/culinari/payment/dto/PaymentDto.java, server/culinari/src/main/java/com/codestates/culinari/payment/entity/Payment.java, server/culinari/src/main/java/com/codestates/culinari/payment/repository/PaymentRepository.java, server/culinari/src/main/java/com/codestates/culinari/payment/repository/querydsl/PaymentRepositoryCustom.java, server/culinari/src/main/java/com/codestates/culinari/payment/repository/querydsl/PaymentRepositoryCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/payment/service/PaymentService.java, server/culinari/src/main/java/com/codestates/culinari/payment/service/impl/PaymentServiceImpl.java
- #83 에서 구현하지 못했던 기능 추가 구현, 부족한 로직 보강
- #57 
- This closes #57
=> [BE] 결제 기능 구현

client/src/App.js, client/src/components/Header.jsx, client/src/pages/search/index.js
검색결과 페이지 구성 레이아웃 구현
없음.
#96 - [FE] 검색결과 페이지 구성 레이아웃 구현
1. 검색결과 페이지 레이아웃 구현
=> [FE] 검색결과 페이지 구성 레이아웃 구현

client/src/components/MainBanner.jsx
메인페이지에서 배너 기본 높이 설정
없음.
#114 [FE] 메인페이지 메인 배너 오류 수정
1. 메인페이지 메인 배너 오류 수정
=> #114 - fix: 메인페이지 배너 높이 설정

client/src/components/ProductItem.jsx, client/src/pages/collection/index.js
신상품 페이지 렌더링 부분 이미지가 없을 경우를 대비하지 않아 클라이언트가 멈춤 현상 해결 및 서버 데이터 연결
없음.
#116 [FE] 상품 리스트 렌더 오류 수정
1. 상품 리스트 렌더 오류 수정
2. 상품 서버 데이터 연결
=> [FE] 상품 리스트 렌더 오류 수정

server/culinari/src/main/java/com/codestates/culinari/order/repository/querydsl/OrdersRepositoryCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/product/controller/ProductCollectionsController.java, server/culinari/src/main/java/com/codestates/culinari/product/dto/response/ProductResponseToPage.java, server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustom.java, server/culinari/src/main/java/com/codestates/culinari/product/repository/querydsl/ProductRepositoryCustomImpl.java, server/culinari/src/main/java/com/codestates/culinari/product/service/ProductService.java, server/culinari/src/main/java/com/codestates/culinari/product/service/impl/ProductServiceImpl.java
- 마이페이지에 존재하는 자주 주문한 상품의 API 구현
- #122 
- #122 에 테스트를 제외한 구현 사항
=> [BE] 마이페이지 - 자주 주문한 상품 기능 구현

client/src/App.js, client/src/components/header/LoginHeader.jsx, client/src/components/header/LogoutHeader.jsx, client/src/components/header/index.js, client/src/components/login/LoginInputForm.jsx, client/src/components/signup/SignupForm.jsx
-  메인 헤더 로그인/로그아웃 디자인
#119 [FE] 메인 헤더 로그인/로그아웃 디자인
=> [FE] 메인 헤더 로그인/로그아웃 디자인

client/src/components/service/OftenDetail.jsx, client/src/components/service/OneOnOne.jsx, client/src/components/service/OneOnOneDetail.jsx, client/src/components/service/OneOnOneItem.jsx, client/src/components/service/ServiceDetailpage.jsx, client/src/styles/OneOnOneStyle.js
- 고객센터 페이지 디자인 수정
#112 [FE] 고객센터 페이지 디자인 수정
- 각 컴포넌트에 '목록으로' 버튼 구현
- css 간격 조정
=> [FE] 고객센터 페이지 디자인 수정

client/src/components/ProductItem.jsx, client/src/components/ProductItemSlider.jsx, client/src/pages/collection/index.js, client/src/pages/mypage/buyItem.js, client/src/pages/mypage/selectItem.js, client/src/pages/search/index.js
ProductItem 컴포넌트 이미지 불러오는 과정에서 오류 발생. props 부분 코드 수정하여 fix.
없음.
#127 [FE] ProductItem props 수정
1. ProductItem props 수정
=> [FE] ProductItem props 수정

client/src/components/signup/GuideModal.jsx, client/src/components/signup/ModalCotainer.jsx, client/src/components/signup/SignupForm.jsx, client/src/styles/signupStyle.js
- 회원가입 페이지 유효성검사 수정
#128 [FE] 회원가입 페이지 유효성검사 수정
=> [FE] 회원가입 페이지 유효성검사 수정

client/src/components/header/LogoutHeader.jsx, client/src/pages/search/index.js
검색 결과 페이지 기능 구현
없음
[FE] 검색 결과 페이지 기능 구현 #131 
1. 서버에 검색 요청하여 받은 상품 리스트 렌더링
2. 낮은 가격순, 높은 가격순 sort 구현
3. 빈 문자열 검색 안되도록 구현
=> [FE] 검색 결과 페이지 기능 구현

client/src/components/ProductItemSlider.jsx
메인페이지 상품 이미지가 없는 경우 클라이언트가 멈춤. 에러 처리
없음.
#152 [FE] 메인페이지 상품 이미지 오류 수정
1. 메인페이지 상품 이미지가 없는 경우 에러 핸들링
=> [FE] 메인페이지 상품 이미지 오류 수정

client/src/pages/productDetail/productAtf/ProductSelection.jsx
장바구니 담기 요청 코드 수정
없음
[FE] 장바구니 담기 요청 코드 수정 #155 
1. 장바구니 담기 요청 코드 수정
=> [FE] 장바구니 담기 요청 코드 수정

client/src/components/header/LogoutHeader.jsx, client/src/pages/search/index.js
카테고리 페이지 레리아웃 및 기능 구현
없음
[FE] 카테고리 페이지 레이아웃 및 기능 구현 #157 
1. 레이아웃 구현
2. 서버 데이터 연결
3. 정렬 기능 구현
=> [FE] 카테고리 페이지 레이아웃 및 기능 구현 #157

client/src/components/cart/CartProductItem.jsx, client/src/pages/cart/index.js
장바구니 삭제 api 수정 부분 코드 수정
없음
[FE] 장바구니 삭제 api 수정 #166 
1. 장바구니 삭제 api 수정 부분 코드 수정
=> [FE] 장바구니 삭제 api 수정

client/src/pages/cart/index.js
장바구니 페이지 css, 배송비 부분 수정
없음
[FE] 장바구니 페이지 css, 배송비 부분 수정 #168 
1. 장바구니 삭제 버튼 부분 포인터 속성 수정
2. 배송비 부분 무료로 수정
=> [FE] 장바구니 페이지 css, 배송비 부분 수정

client/src/App.js, client/src/components/answer/AnswerItem.jsx, client/src/components/answer/AnswerList.jsx, client/src/components/answer/index.js, client/src/components/pay/InfoCheck.jsx, client/src/components/pay/OrderInfo.jsx, client/src/components/pay/PayInfo.jsx, client/src/components/pay/ShipInfo.jsx, client/src/components/pay/index.js, client/src/components/service/AnnouncementItem.jsx, client/src/components/service/ManyQuestionItem.jsx, client/src/components/service/OftenDetail.jsx, client/src/components/service/OneOnOne.jsx, client/src/components/service/OneOnOneDetail.jsx, client/src/components/service/OneOnOneInquiry.jsx, client/src/components/service/OneOnOneItem.jsx, client/src/components/service/ServiceDetailpage.jsx, client/src/components/service/data.json, client/src/components/signup/Post.jsx
=> [FE] 1:1 문의 카테고리,시간 추가 & 1:1 문의 댓글 기능 추가 

client/src/app/reducer/productId2Pay.js, client/src/app/store.js, client/src/components/pay/index.js, client/src/pages/cart/index.js
장바구니 총 주문 금액 데이터 추가
없음.
[FE] 장바구니 스토어 총 주문 금액 데이터 추가 #180 
1. 장바구니 총 주문 데이터 추가
=> [FE] 장바구니 스토어 총 주문 금액 데이터 추가

client/package-lock.json, client/package.json, client/src/components/pay/InfoCheck.jsx, client/src/components/pay/OrderInfo.jsx, client/src/components/pay/PayInfo.jsx, client/src/components/pay/ShipInfo.jsx, client/src/components/pay/index.js
=> [FE] 결제 페이지 Toss 결제 기능 구현

client/src/App.js, client/src/components/header/LogoutHeader.jsx, client/src/pages/collection/CategoryList.jsx, client/src/pages/collection/index.js
신상품, 베스트 기능 구현
없음.
[FE] 신상품, 베스트 페이지 정렬 기능, 카테고리 검색 기능 #165 
1. 신상품 신상품순, 낮은 가격순, 높은 가격순 정렬 기능 구현
2. 카테고리 검색 레이아웃, 기능 구현
=> [FE] 신상품, 베스트 페이지 정렬 기능, 카테고리 검색 기능

client/src/pages/search/index.js
검색 페이지에서 코드 param이 없는 경우 에러 처리
없음
[FE] 검색 기능 오류 수정 #191 
1. 검색 기능 오류 수정
=> [FE] 검색 기능 오류 수정

client/src/components/ProductItemSlider.jsx, client/src/pages/index.js
실제 상품 리스트 렌더링 되도록 수정
슬라이더 버튼 커서 포인터로 수정
없음
[FE] ProductItemSlider 상품 리스트 수정 #195 
1. ProductItemSlider 상품 리스트 수정
2. 슬라이더 버튼 포인터로 수정하기
=> [FE] ProductItemSlider 상품 리스트 수정

client/src/pages/cart/index.js
장바구니 페이지 오류 수정
없음
[FE] 장바구니 페이지 오류 수정 #206 
1. 장바구니 페이지 결제할 상품 없을 경우 베스트 페이지로 리다이렉트
2. 이달의 추천 상품 안뜸 오류 수정
=> [FE] 장바구니 페이지 오류 수정

client/src/components/Pagination.jsx, client/src/components/header/Header.jsx, client/src/pages/cart/index.js, client/src/pages/collection/index.js, client/src/pages/productDetail/productAtf/ProductHeader.jsx, client/src/pages/productDetail/productAtf/ProductSelection.jsx, client/src/pages/productDetail/productContent/CreateInquiry.jsx, client/src/pages/productDetail/productContent/EditInquiry.jsx, client/src/pages/productDetail/productContent/Inquiry.jsx, client/src/pages/productDetail/productContent/Review.jsx, client/src/pages/productDetail/productContent/index.js, client/src/pages/search/index.js
전체적인 오류, css 수정 
없음.
[FE] 전체적인 오류, css 수정 #213 
1. 문의하기 textarea css 수정
2. 문의하기 오류 수정
2. 헤더 검색창 사이즈 수정
3. 헤더 로고 클릭시 메인 페이지 이동하도록 수정
4. 신상품순 낮은 가격순 필터 영역 수정
5. 페이지네이션 css 수정
6. 비로그인 상태에서 장바구니 기능 막음
=> [FE] 전체적인 오류, css 수정 #213

client/src/pages/search/index.js
카테고리 GET 요청 오류 수정
없음
[FE] 카테고리 GET 요청 오류 수정 #218 
1. 카테고리 GET 요청 오류 수정
=> [FE] 카테고리 GET 요청 오류 수정

client/src/pages/productDetail/productContent/CreateInquiry.jsx, client/src/pages/productDetail/productContent/Inquiry.jsx
문의하기 컴포넌트 props 수정, 비로그인 시 로그인 페이지로 유도 구현
없음.
[FE] 문의하기 컴포넌트 props 수정, 비로그인 시 로그인 페이지로 유도 구현 #220 
1. 문의하기 컴포넌트 props 수정
2. 문의하기 로그인 정보 없을 경우 로그인 유도
=> [FE] 문의하기 컴포넌트 props 수정, 비로그인 시 로그인 페이지로 유도 구현

client/src/components/signup/GenderRadio.jsx, client/src/components/signup/SignupForm.jsx
- 회원가입 페이지 GenderRadio setState 에러 해결
=> [FE] 회원가입 페이지 GenderRadio setState 에러 해결

client/src/components/ProductItem.jsx
ProductItem 컴포넌트 가격부분 css 수정
없음
[FE] ProductItem 컴포넌트 가격부분 css 수정 #232 
1. ProductItem 컴포넌트 가격부분 css 수정
=> [FE] ProductItem 컴포넌트 가격부분 css 수정

client/src/pages/productDetail/productContent/Review.jsx, client/src/pages/productDetail/productContent/index.js
후기 요청 쿼리 수정, 후기 상품명 렌더링
없음
[FE] 후기 요청 쿼리 수정, 후기 상품명 렌더링 #242 
1. 후기 요청 쿼리 수정
2. 후기 상품명 렌더링
=> [FE] 후기 요청 쿼리 수정, 후기 상품명 렌더링

client/src/pages/collection/index.js, client/src/pages/productDetail/productContent/Review.jsx, client/src/pages/search/index.js
정렬 버튼 클릭 이벤트 범위 수정
없음
[FE] 정렬 버튼 클릭 이벤트 범위 수정 #243 
1. 정렬 버튼 클릭 이벤트 범위 수정
=> [FE] 정렬 버튼 클릭 이벤트 범위 수정

client/src/pages/productDetail/productContent/index.js
상품 상세페이지 상품 상세 내용 수정
없음.
[FE] 상품 상세페이지 상품 상세 내용 수정 #246 
1. 상품 상세페이지 상품 상세 내용 수정
=> [FE] 상품 상세페이지 상품 상세 내용 수정

client/src/components/cart/CartProductItem.jsx
찜 등록, 취소 시 토스트 메시지 렌더링 구현
없음
[FE] 찜 등록, 취소 시 토스트 메시지 렌더링 구현 #251 
1. 찜 등록, 취소 시 토스트 메시지 렌더링 구현
=> [FE] 찜 등록, 취소 시 토스트 메시지 렌더링 구현

client/src/App.js
불필요한 footer 태그 삭제
없음
[FE] 불필요한 footer 태그 삭제 #254 
불필요한 footer 태그 삭제
=> [FE] 불필요한 footer 태그 삭제

client/src/pages/productDetail/productAtf/ProductHeader.jsx
찜 등록, 취소 시 alert 표시
없음
[FE] 찜 등록, 취소 시 alert 표시 #253 
1. 찜 등록, 취소 시 alert 표시
=> [FE] 찜 등록, 취소 시 alert 표시

client/src/components/signup/SignupForm.jsx, client/src/styles/signupStyle.js
- 회원가입 페이지 주소 input 수정
#259 회원가입 페이지 주소 input 수정
=> #259 - feat: 회원가입 페이지 주소 input 수정

client/src/pages/productDetail/productContent/Review.jsx, client/src/pages/productDetail/productContent/ReviewModal.jsx
상품 후기 이미지 렌더링, 상품 후기 상세 모달 수정
없음
[FE] 상품 후기 이미지 렌더링, 상품 후기 상세 모달 수정 #262 
1. 상품 후기 이미지 렌더링
2. 상품 후기 상세 모달 수정
=> [FE] 상품 후기 이미지 렌더링, 상품 후기 상세 모달 수정

client/src/pages/productDetail/productContent/InquiryDetail.jsx
상품 문의 작성일 수정
없음
[FE] 상품 문의 작성일 수정 #265 
1. 상품 문의 작성일 수정
=> [FE] 상품 문의 작성일 수정

client/.env, client/.gitignore, client/src/components/answer/AnswerItem.jsx, client/src/components/answer/index.js, client/src/components/cart/CartProductItem.jsx, client/src/components/header/Header.jsx, client/src/components/login/LoginInputForm.jsx, client/src/components/pay/SuccessPayment.jsx, client/src/components/pay/index.js, client/src/components/service/OneOnOne.jsx, client/src/components/service/OneOnOneDetail.jsx, client/src/components/signup/ModalCotainer.jsx, client/src/components/signup/SignupForm.jsx, client/src/constants/BASE_URL.js, client/src/pages/cart/index.js, client/src/pages/collection/index.js, client/src/pages/index.js, client/src/pages/productDetail/index.js, client/src/pages/productDetail/productAtf/ProductHeader.jsx, client/src/pages/productDetail/productAtf/ProductSelection.jsx, client/src/pages/productDetail/productContent/CreateInquiry.jsx, client/src/pages/productDetail/productContent/EditInquiry.jsx, client/src/pages/productDetail/productContent/Inquiry.jsx, client/src/pages/productDetail/productContent/InquiryDetail.jsx, client/src/pages/productDetail/productContent/Review.jsx, client/src/pages/search/index.js
요청 url 환경 변수로 수정
없음
[FE] API 요청 url 모두 env로 변경 #268 
1. API 요청 url 모두 env로 변경
2. env 파일 삭제, gitignore env 파일 추가
=> [FE] API 요청 url 모두 env로 변경

client/src/pages/productDetail/productContent/index.js
상품 상세 페이지 nav css 미적용 부분 수정
없음
[FE] 상품 상세 페이지 nav css 적용 부분 수정 #271 
1. 상품 상세 페이지 nav css 미적용 부분 수정
=> [FE] 상품 상세 페이지 nav css 미적용 부분 수정
